name: Java CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean compile
      working-directory: testcase-215-commits
      env:
        ADD: "en-US%0d%0aSet-Cookie:evil=1"

    - name: Run tests
      run: mvn test
      working-directory: testcase-215-commits
      env:
        ADD: "en-US%0d%0aSet-Cookie:evil=1"
